# Generated by Django 5.0.6 on 2024-06-08 12:19

import django.db.models.deletion
import linkedai.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedai', '0003_remove_user_is_admin_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=linkedai.models.upload_to)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
