# Generated by Django 5.0.6 on 2024-06-08 13:14

import django.db.models.deletion
import linkedai.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedai', '0004_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='moderadores',
            field=models.ManyToManyField(related_name='clases_moderadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clase',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clase',
            name='id',
            field=models.CharField(default=linkedai.models.generate_unique_id, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('archivos', models.FileField(blank=True, null=True, upload_to='posts/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkedai.clase')),
            ],
        ),
    ]
