# Generated by Django 5.0.6 on 2024-06-08 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedai', '0005_clase_moderadores_alter_clase_creador_alter_clase_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='clases_unidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
